tp-nt1/Models/Diagnostico.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace tp_nt1.Models
{
    public class Diagnostico
    {
        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [MaxLength(250, ErrorMessage = "{0} admite un máximo de {1} caracteres")]
        public string Descripcion { get; set; }
 
        [MaxLength(250, ErrorMessage = "{0} admite un máximo de {1} caracteres")]
        public string Recomendacion { get; set; }

        [ForeignKey(nameof(Epicrisis))]
        public Guid EpicrisisId { get; set; }
        public Epicrisis Epicrisis { get; set; }
    }
}

tp-nt1/Controllers/DiagnosticosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tp_nt1.Database;
using tp_nt1.Models;
using tp_nt1.Models.Enums;

namespace tp_nt1a_4.Controllers
{
    [Authorize]
    public class DiagnosticosController : Controller
    {
        private readonly HistoriaClinicaDbContext _context;

        public DiagnosticosController(HistoriaClinicaDbContext context)
        {
            _context = context;
        }
        // GET: Diagnosticos/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var diagnostico = await _context.Diagnosticos
                .Include(d => d.Epicrisis)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (diagnostico == null)
            {
                return NotFound();
            }

            return View(diagnostico);
        }

        // GET: Diagnosticos/Create
        [Authorize(Roles = "Empleado,Profesional")]
        public IActionResult Create()
        {
            TempData["episodioId"] = TempData["episodioId"];
            if (User.IsInRole(nameof(Rol.Empleado)))
            {
                return View("CreateEmpleado");
            }
            return View();
        }

        // POST: Diagnosticos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Profesional))]
        public async Task<IActionResult> Create(Diagnostico diagnostico, Guid episodioId)
        {
            if (ModelState.IsValid)
            {
                diagnostico.Id = Guid.NewGuid();

                var epicrisis = new Epicrisis();
                epicrisis.Id = Guid.NewGuid();
                epicrisis.FechaYHora = DateTime.Now;
                epicrisis.Diagnostico = diagnostico;
                epicrisis.ProfesionalId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                epicrisis.EpisodioId = episodioId;
                diagnostico.Epicrisis = epicrisis;
                _context.Add(diagnostico);
                var episodio = _context.Episodios.Find(episodioId);
                episodio.EstadoAbierto = false;
                episodio.FechaYHoraCierre = DateTime.Now;
                episodio.FechaYHoraAlta = DateTime.Now;
                await _context.SaveChangesAsync();         
                return RedirectToAction("Details", "Epicrisis", new { id = epicrisis.Id });
            }
            return View(diagnostico);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Empleado))]
        public async Task<IActionResult> CreateEmpleado(Diagnostico diagnostico, Guid episodioId)
        {
            if (ModelState.IsValid)
            {
                diagnostico.Id = Guid.NewGuid();

                var epicrisis = new Epicrisis();
                epicrisis.Id = Guid.NewGuid();
                epicrisis.FechaYHora = DateTime.Now;
                epicrisis.Diagnostico = diagnostico;
                epicrisis.EpisodioId = episodioId;
                diagnostico.Epicrisis = epicrisis;
                _context.Add(diagnostico);
                var episodio = _context.Episodios.Find(episodioId);
                episodio.EstadoAbierto = false;
                episodio.FechaYHoraCierre = DateTime.Now;
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Epicrisis", new { id = epicrisis.Id });
            }
            ViewData["EpicrisisId"] = new SelectList(_context.Epicrisis, "Id", "Id", diagnostico.EpicrisisId);
            return View(diagnostico);
        }
    }
}

tp-nt1/Controllers/EpicrisisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tp_nt1.Database;
using tp_nt1.Models;
using tp_nt1.Models.Enums;

namespace tp_nt1a_4.Controllers
{
    [Authorize]
    public class EpicrisisController : Controller
    {
        private readonly HistoriaClinicaDbContext _context;

        public EpicrisisController(HistoriaClinicaDbContext context)
        {
            _context = context;
        }

        // GET: Epicrisis/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var epicrisis = await _context.Epicrisis
                .Include(e => e.Episodio)
                .Include(e => e.Profesional)
                .Include(e => e.Diagnostico)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (epicrisis == null)
            {
                return NotFound();
            }
            var diagnosticoId = epicrisis.Diagnostico.Id;
            TempData["diagnosticoId"] = diagnosticoId;
            return View(epicrisis);
        }
    }
}

tp-nt1/Controllers/EpisodiosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using tp_nt1.Database;
using tp_nt1.Models;

namespace tp_nt1a_4.Controllers
{
    [Authorize]
    public class EpisodiosController : Controller
    {
        private readonly HistoriaClinicaDbContext _context;

        public EpisodiosController(HistoriaClinicaDbContext context)
        {
            _context = context;
        }

        // GET: Episodios/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var episodio = await _context.Episodios
                .Include(e => e.EmpleadoRegistra)
                .Include(e => e.HistoriaClinica)
                .Include(e => e.Epicrisis)
                .FirstOrDefaultAsync(m => m.Id == id);
     
            if (episodio == null)
            {
                return NotFound();
            }

            TempData["pacienteId"] = _context.HistoriasClinicas.Find(episodio.HistoriaId).PacienteId;

            if (!episodio.EstadoAbierto)
            {
                var epicrisis = episodio.Epicrisis;
                var epicrisisId = epicrisis.Id;
                TempData["epicrisisId"] = epicrisisId;
            }
            return View(episodio);
        }

        // GET: Episodios/Create
        [Authorize(Roles = "Empleado")]
        public IActionResult Create(Guid hClinicaId)
        {
            ViewBag.pacienteId = _context.HistoriasClinicas.Find(hClinicaId).PacienteId;
            ViewBag.hClinicaId = hClinicaId;
            return View();
        }

        // POST: Episodios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Empleado")]
        public async Task<IActionResult> Create(Episodio episodio, Guid hClinicaId)
        {
            if (ModelState.IsValid)
            {
                episodio.EstadoAbierto = true;
                episodio.Id = Guid.NewGuid();
                episodio.FechaYHoraInicio = DateTime.Now;
                episodio.HistoriaId = hClinicaId;
                episodio.EmpleadoId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

                _context.Add(episodio);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Pacientes");
            }

            return View(episodio);
        }

        public async Task<IActionResult> MiEpisodio(Guid id)
        {
            var episodio = await _context.Episodios
                  .Include(e => e.EmpleadoRegistra)
                  .Include(e => e.HistoriaClinica)
                  .Include(e => e.RegistroEvoluciones)
                  .FirstOrDefaultAsync(m => m.Id == id);
            return View(episodio);
        }

        [HttpPost]
        [Authorize(Roles = "Profesional")]
        public IActionResult PreCerrarEpisodio(Guid id)
        {
            var episodioDb = _context.Episodios
                .Include(episodio => episodio.RegistroEvoluciones)
                .FirstOrDefault(episodio => episodio.Id == id);

            if (episodioDb.EstadoAbierto)
            {
                if (episodioDb.RegistroEvoluciones.Any(evolucion => evolucion.EstadoAbierto))
                {
                    ViewBag.Error = "Hay evoluciones abiertas en este episodio";
                    return RedirectToAction("Details", id);
                }
                TempData["episodioId"] = id;
                return RedirectToAction("Create", "Diagnosticos");
            }
            return RedirectToAction("Details", new { id });
        }

        [HttpPost]
        [Authorize(Roles = "Empleado")]
        public IActionResult PreCerrarEpisodioAdministrativo(Guid id)
        {
            var episodioDb = _context.Episodios
                .FirstOrDefault(episodio => episodio.Id == id);

            if (episodioDb.EstadoAbierto && episodioDb.RegistroEvoluciones == null)
            {
                TempData["episodioId"] = id;
                return RedirectToAction("Create", "Diagnosticos");
            }
            return RedirectToAction("Details", new { id });
        }
    }
}


tp-nt1/Views/Diagnosticos/Create.cshtml
@model tp_nt1.Models.Diagnostico

@{
    ViewData["Title"] = "Crear";
}

<h4>Diagnostico</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <input type="hidden" name="episodioId" value="@TempData["episodioId"]"/>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <textarea asp-for="Descripcion" class="form-control" ></textarea>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Recomendacion" class="control-label"></label>
                <textarea asp-for="Recomendacion" class="form-control" ></textarea>
                <span asp-validation-for="Recomendacion" class="text-danger"></span>
            </div>          
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-outline-info btn-sm" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-info btn-sm" asp-controller="Episodios" asp-action="Details" asp-route-id="@TempData["episodioId"]">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

tp-nt1/Views/Diagnosticos/CreateEmpleado.cshtml
@model tp_nt1.Models.Diagnostico

@{
    ViewData["Title"] = "CrearEmpleado";
}

<h4>Diagnostico</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateEmpleado">
            <input type="hidden" name="episodioId" value="@TempData["episodioId"]"/>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <textarea asp-for="Descripcion" class="form-control" ></textarea>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>         
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-outline-info btn-sm" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-info btn-sm" asp-controller="Episodios" asp-action="Details" asp-route-id="@TempData["episodioId"]">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

tp-nt1/Views/Diagnosticos/Details.cshtml
@model tp_nt1.Models.Diagnostico

@{
    ViewData["Title"] = "Detalle";
}

<div>
    <h4>Diagnostico</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Recomendacion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Recomendacion)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-outline-info btn-sm" asp-controller="Epicrisis" asp-action="Details" asp-route-id="@Model.EpicrisisId">Volver</a>
</div>