tp-nt1/Models/Episodio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace tp_nt1.Models
{
    public class Episodio
    {
        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [MaxLength(100, ErrorMessage = "{0} admite un máximo de {1} caracteres")]
        public string Motivo { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [MaxLength(250, ErrorMessage = "{0} admite un máximo de {1} caracteres")]
        public string Descripcion { get; set; }

        [Display(Name = "Fecha de inicio")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}")]
        public DateTime FechaYHoraInicio { get; set; }

        [Display(Name = "Fecha del alta")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}")]
        public DateTime? FechaYHoraAlta { get; set; }

        [Display(Name = "Fecha de cierre")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}")]
        public DateTime? FechaYHoraCierre { get; set; }

        [Display(Name = "Estado abierto")]
        public bool EstadoAbierto { get; set; }

        public List<Evolucion> RegistroEvoluciones { get; set; }

        public Epicrisis Epicrisis { get; set; }
       
        [ForeignKey(nameof(Empleado))]
        public Guid EmpleadoId { get; set; }

        public Empleado EmpleadoRegistra { get; set; }

        [ForeignKey(nameof(HistoriaClinica))]
        public Guid HistoriaId { get; set; }
        public HistoriaClinica HistoriaClinica { get; set; }
    }
}

tp-nt1/Controllers/EpicrisisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tp_nt1.Database;
using tp_nt1.Models;
using tp_nt1.Models.Enums;

namespace tp_nt1a_4.Controllers
{
    [Authorize]
    public class EpicrisisController : Controller
    {
        private readonly HistoriaClinicaDbContext _context;

        public EpicrisisController(HistoriaClinicaDbContext context)
        {
            _context = context;
        }

        // GET: Epicrisis/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var epicrisis = await _context.Epicrisis
                .Include(e => e.Episodio)
                .Include(e => e.Profesional)
                .Include(e => e.Diagnostico)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (epicrisis == null)
            {
                return NotFound();
            }
            var diagnosticoId = epicrisis.Diagnostico.Id;
            TempData["diagnosticoId"] = diagnosticoId;
            return View(epicrisis);
        }
    }
}

tp-nt1/Controllers/EpisodiosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using tp_nt1.Database;
using tp_nt1.Models;

namespace tp_nt1a_4.Controllers
{
    [Authorize]
    public class EpisodiosController : Controller
    {
        private readonly HistoriaClinicaDbContext _context;

        public EpisodiosController(HistoriaClinicaDbContext context)
        {
            _context = context;
        }

        // GET: Episodios/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var episodio = await _context.Episodios
                .Include(e => e.EmpleadoRegistra)
                .Include(e => e.HistoriaClinica)
                .Include(e => e.Epicrisis)
                .FirstOrDefaultAsync(m => m.Id == id);
     
            if (episodio == null)
            {
                return NotFound();
            }

            TempData["pacienteId"] = _context.HistoriasClinicas.Find(episodio.HistoriaId).PacienteId;

            if (!episodio.EstadoAbierto)
            {
                var epicrisis = episodio.Epicrisis;
                var epicrisisId = epicrisis.Id;
                TempData["epicrisisId"] = epicrisisId;
            }
            return View(episodio);
        }

        // GET: Episodios/Create
        [Authorize(Roles = "Empleado")]
        public IActionResult Create(Guid hClinicaId)
        {
            ViewBag.pacienteId = _context.HistoriasClinicas.Find(hClinicaId).PacienteId;
            ViewBag.hClinicaId = hClinicaId;
            return View();
        }

        // POST: Episodios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Empleado")]
        public async Task<IActionResult> Create(Episodio episodio, Guid hClinicaId)
        {
            if (ModelState.IsValid)
            {
                episodio.EstadoAbierto = true;
                episodio.Id = Guid.NewGuid();
                episodio.FechaYHoraInicio = DateTime.Now;
                episodio.HistoriaId = hClinicaId;
                episodio.EmpleadoId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

                _context.Add(episodio);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Pacientes");
            }

            return View(episodio);
        }

        public async Task<IActionResult> MiEpisodio(Guid id)
        {
            var episodio = await _context.Episodios
                  .Include(e => e.EmpleadoRegistra)
                  .Include(e => e.HistoriaClinica)
                  .Include(e => e.RegistroEvoluciones)
                  .FirstOrDefaultAsync(m => m.Id == id);
            return View(episodio);
        }

        [HttpPost]
        [Authorize(Roles = "Profesional")]
        public IActionResult PreCerrarEpisodio(Guid id)
        {
            var episodioDb = _context.Episodios
                .Include(episodio => episodio.RegistroEvoluciones)
                .FirstOrDefault(episodio => episodio.Id == id);

            if (episodioDb.EstadoAbierto)
            {
                if (episodioDb.RegistroEvoluciones.Any(evolucion => evolucion.EstadoAbierto))
                {
                    ViewBag.Error = "Hay evoluciones abiertas en este episodio";
                    return RedirectToAction("Details", id);
                }
                TempData["episodioId"] = id;
                return RedirectToAction("Create", "Diagnosticos");
            }
            return RedirectToAction("Details", new { id });
        }

        [HttpPost]
        [Authorize(Roles = "Empleado")]
        public IActionResult PreCerrarEpisodioAdministrativo(Guid id)
        {
            var episodioDb = _context.Episodios
                .FirstOrDefault(episodio => episodio.Id == id);

            if (episodioDb.EstadoAbierto && episodioDb.RegistroEvoluciones == null)
            {
                TempData["episodioId"] = id;
                return RedirectToAction("Create", "Diagnosticos");
            }
            return RedirectToAction("Details", new { id });
        }
    }
}


tp-nt1/Controllers/EvolucionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tp_nt1.Database;
using tp_nt1.Models;
using tp_nt1.Models.Enums;

namespace tp_nt1a_4.Controllers
{
    [Authorize]
    public class EvolucionesController : Controller
    {
        private readonly HistoriaClinicaDbContext _context;

        public EvolucionesController(HistoriaClinicaDbContext context)
        {
            _context = context;
        }

        // GET: Evoluciones/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evolucion = await _context.Evoluciones
                .Include(e => e.Episodio)
                .Include(e => e.Notas)
                .Include(e => e.Profesional)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (evolucion == null)
            {
                return NotFound();
            }

            return View(evolucion);
        }

        // GET: Evoluciones/Create
        [Authorize(Roles = nameof(Rol.Profesional))]
        public IActionResult Create(Guid episodioId)
        {
            ViewBag.episodioId = episodioId;
            return View();
        }

        // POST: Evoluciones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = nameof(Rol.Profesional))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Evolucion evolucion,Guid episodioId)
        {
            if (ModelState.IsValid)
            {
                evolucion.Id = Guid.NewGuid();
                evolucion.FechaYHoraInicio = DateTime.Now;
                evolucion.ProfesionalId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                evolucion.EpisodioId = episodioId;
                evolucion.EstadoAbierto = true;
                _context.Add(evolucion);
                await _context.SaveChangesAsync();
                ViewBag.episodioId = episodioId;

                return RedirectToAction("Details",new { id = evolucion.Id });
            }
          
            return View(evolucion);
        }
 
        private bool EvolucionExists(Guid id)
        {
            return _context.Evoluciones.Any(e => e.Id == id);
        }
        
        public async Task<IActionResult> MiEvolucion(Guid evolucionId)
        {
            var evolucion = await _context.Evoluciones
                  .Include(e => e.Notas)
                  .FirstOrDefaultAsync(m => m.Id == evolucionId);  
            return View(evolucion);
        }

        // GET: Evoluciones/Edit/5
        public async Task<IActionResult> CerrarEvolucion(Guid evolucionId)
        {
            var evolucion = await _context.Evoluciones.FindAsync(evolucionId);
            if (evolucion == null)
            {
                return NotFound();
            }
     
            return View(evolucion);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CerrarEvolucion(Evolucion evolucion)
        {
            var evolucionDb = _context.Evoluciones.Find(evolucion.Id);
            try
                {
                
                    if (evolucionDb.EstadoAbierto)
                    {
                        evolucionDb.FechaYHoraAlta = evolucion.FechaYHoraAlta;
                        evolucionDb.EstadoAbierto = false;
                        evolucionDb.FechaYHoraCierre = DateTime.Now;
                        await _context.SaveChangesAsync();
                    }
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EvolucionExists(evolucion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("MiEpisodio","Episodios", new {id = evolucionDb.EpisodioId});
        }
    }
}

tp-nt1/Views/Episodios/Create.cshtml
@model tp_nt1.Models.Episodio

@{
    ViewData["Title"] = "Crear";
}
<h4>Episodio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <input type="hidden" name="hClinicaId" value="@ViewBag.hClinicaId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Motivo" class="control-label"></label>
                <textarea asp-for="Motivo" class="form-control">Motivo</textarea>
                <span asp-validation-for="Motivo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <textarea asp-for="Descripcion" class="form-control">Descripci?n</textarea>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-outline-info btn-sm" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-info btn-sm" asp-controller="HistoriasClinicas" asp-action="UnaHistoriaClinica" asp-route-pacienteId="@ViewBag.pacienteId">Volver</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

tp-nt1/Views/Episodios/Details.cshtml
@model tp_nt1.Models.Episodio

@{
    ViewData["Title"] = "Detalle";
}


<div>
    <h4>Episodio</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Motivo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Motivo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaYHoraInicio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaYHoraInicio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaYHoraAlta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaYHoraAlta)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaYHoraCierre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaYHoraCierre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EstadoAbierto)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EstadoAbierto)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-outline-info btn-sm" asp-controller="Episodios" asp-action="MiEpisodio" asp-route-id="@Model.Id">Ver Evoluciones</a>
    @if (User.IsInRole(nameof(Rol.Profesional)) && Model.EstadoAbierto && Model.RegistroEvoluciones != null)
    {
<form asp-action="PreCerrarEpisodio">
    <input type="hidden" name="id" value="@Model.Id" />
    <div class="text-danger">
        @ViewBag.Error
    </div>
    <button type="submit" class="btn btn-outline-info btn-sm">Cerrar episodio</button>
</form>}

    @if (User.IsInRole(nameof(Rol.Empleado)) && Model.EstadoAbierto && Model.RegistroEvoluciones == null)
    {
<form asp-action="PreCerrarEpisodioAdministrativo">
    <input type="hidden" name="id" value="@Model.Id" />
    <button type="submit" class="btn btn-outline-info btn-sm">Cerrar episodio</button>
</form>}

    @if (!Model.EstadoAbierto)
    {
<a class="btn btn-outline-info btn-sm" asp-controller="Epicrisis" asp-action="Details" asp-route-id="@TempData["epicrisisId"]">Ver Epicrisis</a>}

    @if (User.IsInRole(nameof(Rol.Paciente)))
    {
        <a class="btn btn-outline-info btn-sm" asp-controller="HistoriasClinicas" asp-action="MiHistoriaClinica">Volver</a>
    }
    else
    {
        <a class="btn btn-outline-info btn-sm" asp-controller="HistoriasClinicas" asp-action="UnaHistoriaClinica" asp-route-pacienteId="@TempData["pacienteId"]">Volver</a>
    }
</div>


tp-nt1/Views/Episodios/MiEpisodio.cshtml
@model tp_nt1.Models.Episodio

@{
    var evoluciones = Model.RegistroEvoluciones;
}


<table class="table table-hover">
    <thead>
        <tr>
            <th>
                <h5>Evoluciones</h5>
                @if (User.IsInRole(nameof(Rol.Profesional)) && Model.EstadoAbierto)
                {
                    <a class="btn btn-outline-info" asp-controller="Evoluciones" asp-action="Create" asp-route-episodioId="@Model.Id">+ Crear Evolucion</a>
                }
            </th>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => evoluciones[0].DescripcionAtencion)
            </th>
            <th>
                @Html.DisplayNameFor(model => evoluciones[0].EstadoAbierto)
            </th>
            <th>
                @Html.DisplayNameFor(model => evoluciones[0].FechaYHoraCierre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var e in evoluciones)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelE => e.DescripcionAtencion)
            </td>
            <td>
                @Html.DisplayFor(modelE => e.EstadoAbierto)
            </td>
            <td>
                @Html.DisplayFor(modelE => e.FechaYHoraCierre)
            </td>
            <td>
            <td>
                <a class="btn btn-outline-info btn-sm" asp-controller="Evoluciones" asp-action="Details" asp-route-id="@e.Id">Ver evolucion</a>
            </td>
        </tr>
        }
    </tbody>
</table>
<a class="btn btn-outline-info btn-sm" asp-action="Details" asp-route-id="@Model.Id">Volver</a>