tp-nt1/Controllers/EvolucionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tp_nt1.Database;
using tp_nt1.Models;
using tp_nt1.Models.Enums;

namespace tp_nt1a_4.Controllers
{
    [Authorize]
    public class EvolucionesController : Controller
    {
        private readonly HistoriaClinicaDbContext _context;

        public EvolucionesController(HistoriaClinicaDbContext context)
        {
            _context = context;
        }

        // GET: Evoluciones/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evolucion = await _context.Evoluciones
                .Include(e => e.Episodio)
                .Include(e => e.Notas)
                .Include(e => e.Profesional)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (evolucion == null)
            {
                return NotFound();
            }

            return View(evolucion);
        }

        // GET: Evoluciones/Create
        [Authorize(Roles = nameof(Rol.Profesional))]
        public IActionResult Create(Guid episodioId)
        {
            ViewBag.episodioId = episodioId;
            return View();
        }

        // POST: Evoluciones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = nameof(Rol.Profesional))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Evolucion evolucion,Guid episodioId)
        {
            if (ModelState.IsValid)
            {
                evolucion.Id = Guid.NewGuid();
                evolucion.FechaYHoraInicio = DateTime.Now;
                evolucion.ProfesionalId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                evolucion.EpisodioId = episodioId;
                evolucion.EstadoAbierto = true;
                _context.Add(evolucion);
                await _context.SaveChangesAsync();
                ViewBag.episodioId = episodioId;

                return RedirectToAction("Details",new { id = evolucion.Id });
            }
          
            return View(evolucion);
        }
 
        private bool EvolucionExists(Guid id)
        {
            return _context.Evoluciones.Any(e => e.Id == id);
        }
        
        public async Task<IActionResult> MiEvolucion(Guid evolucionId)
        {
            var evolucion = await _context.Evoluciones
                  .Include(e => e.Notas)
                  .FirstOrDefaultAsync(m => m.Id == evolucionId);  
            return View(evolucion);
        }

        // GET: Evoluciones/Edit/5
        public async Task<IActionResult> CerrarEvolucion(Guid evolucionId)
        {
            var evolucion = await _context.Evoluciones.FindAsync(evolucionId);
            if (evolucion == null)
            {
                return NotFound();
            }
     
            return View(evolucion);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CerrarEvolucion(Evolucion evolucion)
        {
            var evolucionDb = _context.Evoluciones.Find(evolucion.Id);
            try
                {
                
                    if (evolucionDb.EstadoAbierto)
                    {
                        evolucionDb.FechaYHoraAlta = evolucion.FechaYHoraAlta;
                        evolucionDb.EstadoAbierto = false;
                        evolucionDb.FechaYHoraCierre = DateTime.Now;
                        await _context.SaveChangesAsync();
                    }
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EvolucionExists(evolucion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("MiEpisodio","Episodios", new {id = evolucionDb.EpisodioId});
        }
    }
}

tp-nt1/Controllers/NotasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tp_nt1.Database;
using tp_nt1.Models;
using tp_nt1.Models.Enums;

namespace tp_nt1a_4.Controllers
{
    [Authorize]
    public class NotasController : Controller
    {
        private readonly HistoriaClinicaDbContext _context;

        public NotasController(HistoriaClinicaDbContext context)
        {
            _context = context;
        }

        // GET: Notas/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nota = await _context.Notas
                .Include(n => n.Empleado)
                .Include(n => n.Profesional)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nota == null)
            {
                return NotFound();
            }
            var evolucion = _context.Evoluciones.Find(nota.EvolucionId);
            ViewBag.Estado = evolucion.EstadoAbierto;
            return View(nota);
        }

        // GET: Notas/Create
        [Authorize(Roles = "Empleado,Profesional")]
        public IActionResult Create(Guid evolucionId)
        {

            ViewBag.evolucionId = evolucionId;
            return View();
        }

        // POST: Notas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Empleado,Profesional")]
        public async Task<IActionResult> Create(Guid evolucionId, Nota nota)
        {
            if (ModelState.IsValid)
            {
                nota.Id = Guid.NewGuid();
                nota.FechaYHora = DateTime.Now;
                nota.EvolucionId = evolucionId;
                var usuarioId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                if(User.IsInRole(nameof(Rol.Empleado)))
                {
                    nota.EmpleadoId = usuarioId;
                }
                else
                {
                    nota.ProfesionalId = usuarioId;
                }
                _context.Add(nota);
                await _context.SaveChangesAsync();
                ViewBag.EvolucionId = evolucionId;
                return RedirectToAction("Details", new { id = nota.Id });
            }

            return View(nota);
        }
    }
}

tp-nt1/Views/Evoluciones/CerrarEvolucion.cshtml
@model tp_nt1.Models.Evolucion

@{
    ViewData["Title"] = "Cerrar Evolucion";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="CerrarEvolucion">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />         
            <div class="form-group">
                <label asp-for="FechaYHoraAlta" class="control-label">Fecha y hora del alta</label>
                <input asp-for="FechaYHoraAlta" class="form-control" />
                <span asp-validation-for="FechaYHoraAlta" class="text-danger">Fecha y Hora del alta</span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-outline-info btn-sm"  />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-info btn-sm" asp-controller="Episodios" asp-action="MiEpisodio" asp-route-id="@Model.EpisodioId">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

tp-nt1/Views/Evoluciones/Create.cshtml
@model tp_nt1.Models.Evolucion

@{
    ViewData["Title"] = "Crear";
}

<h4>Evolucion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <input type="hidden" name="episodioId" value="@ViewBag.episodioId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DescripcionAtencion" class="control-label">Descripcion</label>
                <textarea asp-for="DescripcionAtencion" class="form-control"></textarea>
                <span asp-validation-for="DescripcionAtencion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-outline-info btn-sm" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-info btn-sm" asp-controller="Episodios" asp-action="MiEpisodio" asp-route-id="@ViewBag.episodioId">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

tp-nt1/Views/Evoluciones/Details.cshtml
@model tp_nt1.Models.Evolucion

@{
    ViewData["Title"] = "Detalles";
}

<div>
    <h4>Evolucion</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaYHoraInicio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaYHoraInicio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaYHoraAlta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaYHoraAlta)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaYHoraCierre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaYHoraCierre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DescripcionAtencion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DescripcionAtencion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EstadoAbierto)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EstadoAbierto)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Episodio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Episodio.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Profesional)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Profesional.Apellido)
        </dd>
    </dl>
</div>
<div>

    <a class="btn btn-outline-info btn-sm" asp-controller="Evoluciones" asp-action="MiEvolucion" asp-route-evolucionId="@Model.Id">Ver notas</a>
    @if (User.IsInRole(nameof(Rol.Profesional)))
    {
        if (Model.EstadoAbierto)
        {
                    <a class="btn btn-outline-info btn-sm" asp-controller="Evoluciones" asp-action="CerrarEvolucion" asp-route-evolucionId="@Model.Id">Cerrar evolucion</a>}
        }
        <a class="btn btn-outline-info btn-sm" asp-controller="Episodios" asp-action="MiEpisodio" asp-route-id="@Model.EpisodioId">Volver</a>
</div>

tp-nt1/Views/Evoluciones/MiEvolucion.cshtml
@model tp_nt1.Models.Evolucion

@{
    var notas = Model.Notas;
}


<table class="table table-hover">
    <thead>
        <tr>
            <th>
                <h5>Notas</h5>
                @if ((User.IsInRole(nameof(Rol.Profesional)) || User.IsInRole(nameof(Rol.Empleado))) && Model.EstadoAbierto)
                {
                    <a class="btn btn-outline-info" asp-controller="Notas" asp-action="Create" asp-route-evolucionId="@Model.Id">+ Agregar nota</a>
                }
            </th>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(modelE => notas[0].Mensaje)
            </th>
            <th>
                @Html.DisplayNameFor(modelE => notas[0].FechaYHora)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var n in notas)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelE => n.Mensaje)
            </td>
            <td>
                @Html.DisplayFor(modelE => n.FechaYHora)
            </td>
            <td>
                <a class="btn btn-outline-info btn-sm" asp-controller="Notas" asp-action="Details" asp-route-id="@n.Id">Ver nota</a>
            </td>
        </tr>
        }
    </tbody>
</table>

<a class="btn btn-outline-info btn-sm" asp-action="Details" asp-route-id="@Model.Id">Volver</a>