tp-nt1/Controllers/PacientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tp_nt1.Database;
using tp_nt1.Extensions;
using tp_nt1.Models;

namespace tp_nt1a_4.Controllers
{
    [Authorize]
    public class PacientesController : Controller
    {
        private readonly HistoriaClinicaDbContext _context;

        public PacientesController(HistoriaClinicaDbContext context)
        {
            _context = context;
        }

        // GET: Pacientes
        [Authorize(Roles = "Profesional,Empleado")]
        public async Task<IActionResult> Index()
        {
            var historiaClinicaDbContext = _context.Pacientes.Include(p => p.ObraSocial);
            return View(await historiaClinicaDbContext.ToListAsync());
        }


        [Authorize(Roles = "Profesional")]

        public async Task<IActionResult> MisPacientes()
        {
            var profesionalId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var historiaClinicaDbContext = _context.Pacientes.Include(p => p.ObraSocial)
                .Where(p => p.HistoriaClinica.Episodios.Any(e => e.RegistroEvoluciones.Any(y => y.ProfesionalId == profesionalId)));
            var historias = await historiaClinicaDbContext.ToListAsync();
            return View(historias);
        }



        // GET: Pacientes/Details/5
        [Authorize]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _context.Pacientes
                .Include(p => p.ObraSocial)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (paciente == null)
            {
                return NotFound();
            }

            return View(paciente);
        }

        // GET: Pacientes/Create
        [AllowAnonymous]
        public IActionResult Create()
        {
            ViewData["ObraSocialId"] = new SelectList(_context.ObrasSociales, "Id", "Nombre");
            return View();
        }

        // POST: Pacientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Create(Paciente paciente, string pass)
        {
            try
            {
                pass.ValidarPassword();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(nameof(Paciente.Password), ex.Message);
            }

            if (_context.Pacientes.Any(p => p.NombreUsuario == paciente.NombreUsuario))
            {
                ModelState.AddModelError(nameof(Paciente.NombreUsuario), "El nombre de usuario ya se encuentra utilizado");
            }

            if (ModelState.IsValid)
            {
                paciente.Id = Guid.NewGuid();
                paciente.FechaAlta = DateTime.Now;
                paciente.Password = pass.Encriptar();
                paciente.HistoriaClinica = new HistoriaClinica() { PacienteId = paciente.Id, Id = Guid.NewGuid() };
                _context.Add(paciente);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }

            ViewData["ObraSocialId"] = new SelectList(_context.ObrasSociales, "Id", "Nombre", paciente.ObraSocialId);
            return View(paciente);
        }

        // GET: Pacientes/Edit/5
        [Authorize(Roles = "Empleado,Paciente")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _context.Pacientes.FindAsync(id);
            if (paciente == null)
            {
                return NotFound();
            }
            ViewData["ObraSocialId"] = new SelectList(_context.ObrasSociales, "Id", "Nombre", paciente.ObraSocialId);
            return View(paciente);
        }

        // POST: Pacientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Empleado,Paciente")]
        public async Task<IActionResult> Edit(Guid id, Paciente paciente, string pass)
        {
            if (!string.IsNullOrWhiteSpace(pass))
            {
                try
                {
                    pass.ValidarPassword();
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(nameof(Paciente.Password), ex.Message);
                }
            }

            if (id != paciente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(paciente);
                    if (!string.IsNullOrWhiteSpace(pass))
                    {
                        paciente.Password = pass.Encriptar();
                    }
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PacienteExists(paciente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ObraSocialId"] = new SelectList(_context.ObrasSociales, "Id", "Nombre", paciente.ObraSocialId);
            return View(paciente);
        }
  
        private bool PacienteExists(Guid id)
        {
            return _context.Pacientes.Any(e => e.Id == id);
        }
    }
}

tp-nt1/Controllers/ProfesionalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tp_nt1.Database;
using tp_nt1.Extensions;
using tp_nt1.Models;
using tp_nt1.Models.Enums;

namespace tp_nt1a_4.Controllers
{
    [Authorize]
    public class ProfesionalesController : Controller
    {
        private readonly HistoriaClinicaDbContext _context;

        public ProfesionalesController(HistoriaClinicaDbContext context)
        {
            _context = context;
        }

        // GET: Profesionales
        [Authorize(Roles = nameof(Rol.Empleado))]
        public async Task<IActionResult> Index()
        {
            var historiaClinicaDbContext = _context.Profesionales.Include(p => p.Especialidad);
            return View(await historiaClinicaDbContext.ToListAsync());
        }

        // GET: Profesionales/Details/5
        [Authorize(Roles = "Empleado,Profesional")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profesional = await _context.Profesionales
                .Include(p => p.Especialidad)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (profesional == null)
            {
                return NotFound();
            }

            return View(profesional);
        }

        // GET: Profesionales/Create
        [Authorize(Roles = nameof(Rol.Empleado))]
        public IActionResult Create()
        {
            ViewData["EspecialidadId"] = new SelectList(_context.Especialidades, "Id", "Nombre");
            return View();
        }

        // POST: Profesionales/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Empleado))]
        public async Task<IActionResult> Create(Profesional profesional, string pass)
        {
            try
            {
                pass.ValidarPassword();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(nameof(Profesional.Password), ex.Message);
            }

            if (_context.Pacientes.Any(prof => prof.NombreUsuario == profesional.NombreUsuario))
            {
                ModelState.AddModelError(nameof(Profesional.NombreUsuario), "El nombre de usuario ya se encuentra utilizado");
            }

            if (ModelState.IsValid)
            {
                profesional.Id = Guid.NewGuid();
                profesional.FechaAlta = DateTime.Now;
                profesional.Password = pass.Encriptar();
                _context.Add(profesional);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EspecialidadId"] = new SelectList(_context.Especialidades, "Id", "Nombre", profesional.EspecialidadId);
            return View(profesional);
        }

        // GET: Profesionales/Edit/5
        [Authorize(Roles = "Empleado,Profesional")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profesional = await _context.Profesionales.FindAsync(id);
            if (profesional == null)
            {
                return NotFound();
            }
            ViewData["EspecialidadId"] = new SelectList(_context.Especialidades, "Id", "Nombre", profesional.EspecialidadId);
            return View(profesional);
        }

        // POST: Profesionales/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Empleado,Profesional")]
        public async Task<IActionResult> Edit(Guid id, Profesional profesional, string pass)
        {
            if (!string.IsNullOrWhiteSpace(pass))
            {
                try
                {
                    pass.ValidarPassword();
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(nameof(Profesional.Password), ex.Message);
                }
            }

            if (id != profesional.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(profesional);
                    if (!string.IsNullOrWhiteSpace(pass))
                    {
                        profesional.Password = pass.Encriptar();
                    }
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfesionalExists(profesional.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EspecialidadId"] = new SelectList(_context.Especialidades, "Id", "Nombre", profesional.EspecialidadId);
            return View(profesional);
        }   
        private bool ProfesionalExists(Guid id)
        {
            return _context.Profesionales.Any(e => e.Id == id);
        }
    }
}

tp-nt1/Views/Profesionales/Create.cshtml
@model tp_nt1.Models.Profesional

@{
    ViewData["Title"] = "Crear";
}

<h4>Profesional</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Matricula" class="control-label"></label>
                <input asp-for="Matricula" class="form-control" />
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EspecialidadId" class="control-label">Especialidad</label>
                <select asp-for="EspecialidadId" class="form-control" asp-items="ViewBag.EspecialidadId"></select>
            </div>
            <div class="form-group">
                <label asp-for="NombreUsuario" class="control-label">Usuario</label>
                <input asp-for="NombreUsuario" class="form-control" />
                <span asp-validation-for="NombreUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>   
            <div class="form-group">
                <label asp-for="DNI" class="control-label"></label>
                <input asp-for="DNI" class="form-control" />
                <span asp-validation-for="DNI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="password" class="control-label">Password</label>
                <input name="pass" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-outline-info btn-sm" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-info btn-sm" asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

tp-nt1/Views/Profesionales/Details.cshtml
@model tp_nt1.Models.Profesional

@{
    ViewData["Title"] = "Detalle";
}

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Matricula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Especialidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Especialidad.Nombre)
        </dd>
        <dt class = "col-sm-2">
            Usuario
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreUsuario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            Fecha del alta
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaAlta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DNI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DNI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-outline-info btn-sm" asp-action="Edit" asp-route-id="@Model.Id">Actualizar</a>
    @if (User.IsInRole(nameof(Rol.Empleado)))
    {
        <a class="btn btn-outline-info btn-sm" asp-action="Index">Volver</a>
    }
    else
    { 
        <a class="btn btn-outline-info btn-sm" asp-controller="Pacientes" asp-action="MisPacientes">Volver</a>
    }
</div>

tp-nt1/Views/Profesionales/Edit.cshtml
@model tp_nt1.Models.Profesional

@{
    ViewData["Title"] = "Editar";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Matricula" class="control-label">Matricula</label>
                <input asp-for="Matricula" class="form-control" />
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EspecialidadId" class="control-label">Especialidad</label>
                <select asp-for="EspecialidadId" class="form-control" asp-items="ViewBag.EspecialidadId"></select>
                <span asp-validation-for="EspecialidadId" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NombreUsuario" class="control-label">Usuario</label>
                <input asp-for="NombreUsuario" class="form-control" />
                <span asp-validation-for="NombreUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label">Nombre</label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label">Apellido</label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaAlta" class="control-label">Fecha del alta</label>
                <input asp-for="FechaAlta" class="form-control" readonly />
                <span asp-validation-for="FechaAlta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DNI" class="control-label">DNI</label>
                <input asp-for="DNI" class="form-control" />
                <span asp-validation-for="DNI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label">Telefono</label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label">Direccion</label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-outline-info btn-sm" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-info btn-sm" asp-action="Details" asp-route-id="@Model.Id">Volver</a>
</div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

tp-nt1/Views/Profesionales/Index.cshtml
@model IEnumerable<tp_nt1.Models.Profesional>

@{
    ViewData["Title"] = "Index";
}

<p>
    <a class= "btn btn-outline-info" asp-action="Create">+ Nuevo Profesional</a>
</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Matricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Especialidad)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Matricula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Especialidad.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>          
        <td>
            <a class="btn btn-outline-info btn-sm" asp-action="Details" asp-route-id="@item.Id">Ver info</a>
        </td>
        </tr>
}
    </tbody>
</table>